version: '3'
services:
    webapp:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - mock-api-server
        restart: always
        ports:
            - '8080:8080'
        environment:
            - APPRES_CMS_URL=http://appres.nav.no
            - FORELDREPENGESOKNAD_API_URL=http://mock-api-server:8888/rest
            - LOGINSERVICE_URL=http://mock-api-server:8888/local/cookie
            - FP_UTTAK_SERVICE_URL=https://fp-uttak-service.nav.no
        volumes:
          - ./:/webapp
          - ./node_modules:/webapp/node_modules

    mock-api-server:
        build:
            context: ./mock-api
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8888:8888'
        volumes:
          - ./mock-api:/mock-api
          - ./mock-api/node_modules

    cypress-tests:
        image: cypress
        build: 
            context: ./cypress-tests
            dockerfile: Dockerfile
        depends_on:
            - webapp
            - mock-api-server
        environment:
            - CYPRESS_baseUrl=http://webapp:8080
        command: npx cypress run
        volumes:
            - ./cypress-tests/cypress:/app/cypress
            - .//cypress.json:/app/cypress.json
